#include "intro_object.h"

unsigned char *intro_textTop[] =
{
	"CONQUER ALL LEVELS",
	"ESCAPE THE ENEMIES",
	"COLLECT THE GEMS &",
	"BASED OFF PLATFORM",
	"THUS PORTED TO THE",
	"ALL PROGRAMMING BY",
	"DEVKITSMS BUILT BY",
	"BIG THANKS GOES TO",
	"THANKS ALSO OUT TO",
	"NOW GOOD LUCK HERO",
};

unsigned char *intro_textBot[] =
{
	"OF PLATFROM ACTION",
	"& EVADE THE GUARDS",
	"HURRY TO THE EXIT!",
	"STARTER KIT BY XNA",
	"SEGA MASTER SYSTEM",
	"STEVEPRO USING THE",
	"SVERX. THANKS MAN!",
	"ALL @ SMSPOWER.ORG",
	"ERUIZ00+ HAROLDOOP",
	"ADVENTURE AWAITS..!"
};